version: "3.8"
services:
  nuxeo:
    image: fix-sharepoint-hashbang:1.0.0
    env_file: .env
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      NUXEO_DEV: "true"
      NUXEO_CLID:
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
      - lib:/var/lib/nuxeo
      - log:/var/log/nuxeo
      - tmp:/tmp
volumes:
  data: {}
  tmp: {}
  lib: {}
  log: {}
